sudo: false
language: node_js
node_js:
- '4.1'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
  - "$HOME/go_appengine/"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_script:
- npm install -g gulp
script: gulp lint test validate && gulp clean build
#before_install:
#- openssl aes-256-cbc -K $encrypted_8592b1f8cf3c_key -iv $encrypted_8592b1f8cf3c_iv
#  -in client-secret.json.enc -out client-secret.json -d
#after_success:
#- test $TRAVIS_PULL_REQUEST == "true" && exit 0
#- sh scripts/deploy-to-appengine.sh
